### ISSUE TITLE
老伯伯系统

### ISSUE THREAD

**Issue by ruruzhu** [qhzhou/nztrip#39]
1 库存表导出月份   要导出到次年5月的，不能只导出3个月不够
2 库存表单日场次显示顺序   08:00要排在格子的最上面，不能排在下面，看起来很别扭
3 删除库存  界面Ok啦~~~modify库存，我点了删除2018-03-01的，进入我们系统看，库存还在（已确认是假的。。大神还在想。。。）
4 wholesale price   船长界面，查看订单，订单里的wholesale price，显示的是我们跟我们的agent的结算价。应该要显示船长给agent的结算价，原则上是船长给自己的agent的代理价，也就应该是显示我们的成本价。
5 时间  个么什么时间能真的拿出来用啦~~~

**Comment by qhzhou** [comment]
已经拆成单独的issue
